services:
  # Node web service
  - type: web
    name: logchimp-api
    env: node
    repo: https://github.com/logchimp/logchimp
    branch: v0.6.1
    numInstances: 1
    buildCommand: yarn install
    startCommand: yarn start
    autoDeploy: false

  # A static site
  - type: web
    name: logchimp-client
    env: static
    repo: https://github.com/logchimp/theme.git
    buildCommand: yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 12
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: logchimp-database
    # only allow internal connections
    ipAllowList: []
    postgresMajorVersion: 12
